<?php

namespace Tests\Feature\Rating;

use AchievementSeeder;
use App\Achievement;
use App\Point;
use App\Rating;
use App\Student;
use App\User;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class RatingStoreTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(\CategorySeeder::class);
        $this->seed(AchievementSeeder::class);
    }

    /**
     * A basic test example.
     *
     * @return void
     * @test
     */
    public function test_its_redirect_unauthenticated_users()
    {
        $response = $this->post('/rating');
        $response->assertStatus(302);
    }

    public function test_it_redirects_if_user_is_not_admin()
    {
        $user = factory(User::class)->create();
        $this->actingAs($user);

        $this->post('/rating')->assertStatus(403);
    }

    public function test_it_upload_rating_if_all_data_ok()
    {
        $this->withoutExceptionHandling();

        $user = factory(User::class)->create([
            'is_admin' => true
        ]);
        $this->actingAs($user);

        $this->assertCount(0, Rating::all());
        $this->assertCount(0, Point::all());
        $this->assertEquals(1, $adminUserCount = User::count());


        $this->post('/rating',[
            'type' => 1,
            'file' => new UploadedFile(base_path('tests/Stubs/') . '/rating.xls', 'rating.xls'),
            'month' => '2019-09'
        ])->assertStatus(302);

        $this->assertCount(1, Rating::all());
        $this->assertTrue(Point::count() > 0);
        $this->assertEquals(Student::count(), 151);
    }

    public function test_it_awards_points_to_students()
    {
        $expectedPoints = [
            'games' => 650,
            'travels' => 1500,
        ];

        $this->postRating();

        $student = $this->expectedStudent();
        $points = $student->points->keyBy(function (Point $point) {
            return $point->category->name; //TODO: в slug
        });

        $this->assertCount(5, $points);

        foreach ($expectedPoints as $slug => $amount) {
            $this->assertEquals($amount, $points[$slug]->amount);
        }
    }

    public function test_it_award_achievements_to_student()
    {
        $this->postRating();

        $student = $this->expectedStudent();

        $this->assertCount(1, $achievements = $student->achievements);
    }

    public function test_it_awards_get_more_then_1000_points_()
    {

        $achivement = Achievement::where('name', 'Начинающий новичок')->first();
        dd($achivement->students->count());
    }

    protected function expectedStudent()
    {
        return Student::where('name', 'Селюченко Иван')->firstOrFail();
    }

    protected function postRating()
    {
        $user = factory(User::class)->create([
            'is_admin' => true
        ]);
        $this->actingAs($user);

        $this->post('/rating',[
            'type' => 1,
            'file' => new UploadedFile(base_path('tests/Stubs/') . '/rating.xls', 'rating.xls'),
            'month' => '2019-09'
        ]);
    }
}
